articles/urls.py
from django.urls import path, re_path
from articles import views
from .feeds import LatestEntriesFeed

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='home'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('newsletter/', views.control_newsletter, name='control_newsletter'),
    path('about_us/', views.about, name='about'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('terms/', views.terms, name='terms'),
    path('advert/', views.advert, name='advert'),
    path('feed/', LatestEntriesFeed()),
    path('ads.txt/', views.authorized_digital_sellers, name='Authorized_Digital_Sellers'),
    path('<slug:slug>/', views.article_detail, name='detail'),
    path('video/<slug:slug>/', views.video_detail, name='video_detail'),
    re_path('category/(?P<cat_name>[^/]+)/$', views.article_list, name='list'),
    re_path('option/(?P<status>[^/]+)/$', views.options, name='option')

]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('articles.urls', namespace='articles')),
    url('ckeditor', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/forms.py
from django import forms
from .models import NewsletterUser, Newsletter
from django.contrib.auth import (
    authenticate,
    get_user_model

 )

User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={"placeholder": "Your Username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Your Password"}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect Password")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email Address")
    email2 = forms.EmailField(label="Confirm Email")
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "email2",
            "password"
        ]

    def clean_email2(self):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")
        if email != email2:
            raise forms.ValidationError("Email Must Match !")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This Email has already been registered")
        return email


class NewsletterUserSignUpForm(forms.ModelForm):
    email = forms.EmailField(label='', widget=forms.TextInput(attrs={"placeholder": "Your Email Address"}))

    class Meta:
        model = NewsletterUser
        fields = ['email']

        def clean_email(self):
            email = self.cleaned_data.get('email')

            return email


class NewsletterCreationForm(forms.ModelForm):
    subject = forms.CharField(label='Title')
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Newsletter
        fields = ['subject', 'body', 'email', 'status']

articles/views.py
import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from blog.settings import production_settings
from .models import Article, LikeViews, User, Category, NewsletterUser, Newsletter, Video
from django.contrib.contenttypes.models import ContentType
from comments.forms import CommentForm
from comments.models import Comment
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse, Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from articles.utils import get_client_ip
from taggit.models import Tag
from articles.forms import (
    NewsletterUserSignUpForm,
    NewsletterCreationForm,
    UserRegisterForm,
    UserLoginForm
)
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout
)


def index(request):
    articles = Article.objects.all().order_by('-created_on')[:10]
    category = Article.objects.filter(category_ref__name='category').order_by('-created_on')
    news = Article.objects.filter(category_ref__name='politics').order_by('-created_on')[:5]
    life = Article.objects.filter(category_ref__name='business').order_by('-created_on')[:2]
    sport1 = Article.objects.filter(category_ref__name='sports').order_by('-created_on')[:1]
    sport2 = Article.objects.filter(category_ref__name='sports').order_by('-created_on')[1:3]
    sport3 = Article.objects.filter(category_ref__name='sports').order_by('-created_on')[3:5]
    ent1 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[:1]
    ent2 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[1:2]
    ent3 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[2:3]
    ent4 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[3:4]
    pic1 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[:4]
    pic2 = Article.objects.filter(category_ref__name='entertainment').order_by('-created_on')[4:7]
    tech = Article.objects.filter(category_ref__name='world').order_by('-created_on')[:1]
    tech2 = Article.objects.filter(category_ref__name='world').order_by('-created_on')[1:3]
    politics = Article.objects.filter(category_ref__name='news').order_by('-created_on')[:1]
    instance = Article.objects.filter(category_ref__name='news').order_by('-created_on')[1:4]
    obj = Article.objects.all().order_by('-created_on')[1:8]
    post = Article.objects.all().order_by('-created_on')[:1]
    post1 = Article.objects.all().order_by('-created_on')[1:2]
    post2 = Article.objects.all().order_by('-created_on')[2:3]
    post3 = Article.objects.all().order_by('-created_on')[3:4]
    widget = Article.objects.all().order_by('-created_on')[:5]
    video = Video.objects.all()[:3]
    categories = Category.objects.all()[:10]
    cate_more = Category.objects.all()[11:]
    cate_1 = Category.objects.all()[:5]
    cate_2 = Category.objects.all()[6:]
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&APPID=43e8c934e7122d5b40a25fe6b66c7390'
    city = "lagos"
    r = requests.get(url.format(city)).json()
    city_weather = {
        'city': city,
        'temperature': r['main']['temp'],
        'description': r['weather'][0]['description'],
        'icon': r['weather'][0]['icon'],
    }
    forms = NewsletterUserSignUpForm(request.POST or None)
    if forms.is_valid():
        instance = forms.save(commit=False)
        if NewsletterUser.objects.filter(email=instance.email).exists():
            messages.warning(request, "Email Address Already Exists", "alert alert-warning alert-dismissible")
        else:
            instance.save()
            messages.success(request, "Congratulation!, Your Subscription is Successful.",
                             "alert alert-success alert-dismissible")
            subject = "Thank you for joining our Newsletter family"
            from_email = production_settings.EMAIL_HOST_USER
            to_email = [instance.email]
            message = EmailMultiAlternatives(subject=subject, from_email=from_email, to=to_email)
            html_template = get_template("signup_newsletter.html").render()
            message.attach_alternative(html_template, "text/html")
            message.send()
    context = {
        "post": post, "post1": post1, "post2": post2, "post3": post3, "news": news, "obj": obj, "tech": tech,
        "tech2": tech2, "articles": articles, "category": category, "politics": politics, "instance": instance,
        "ent1": ent1, "ent2": ent2, "ent3": ent3, "ent4": ent4, "sport1": sport1, "sport2": sport2, "video": video,
        "sport3": sport3, "life": life, "widget": widget, 'categories': categories, "cate_1": cate_1, "cate_2": cate_2,
        "city_weather": city_weather, "forms": forms, "pic1": pic1, "pic2": pic2, "cate_more": cate_more
    }
    return render(request, 'index.html', context)


def article_detail(request, slug):
    instance = Article.objects.get(slug=slug)
    cat_id = instance.category_ref.id
    related_post = Article.objects.filter(category_ref_id=cat_id)[1:7]
    obj = Article.objects.all().order_by('-created_on')[:10]
    category = Article.objects.filter(category_ref__name='category')
    common_tags = Article.tags.most_common()
    ip = get_client_ip(request)
    if not LikeViews.objects.filter(article_id=instance.id,
                                    action='view', ip=ip).exists():
        new_view = LikeViews()
        new_view.article = Article.objects.get(pk=instance.id)
        new_view.ip = ip
        new_view.action = 'view'
        new_view.save()
        instance.viewcount = instance.viewcount + 1
        instance.save()

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid():
        c_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        email = comment_form.cleaned_data.get('email')
        content_data = comment_form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(
            email=email,
            content_type=content_type,
            object_id=obj_id,
            content=content_data,
            parent=parent_obj,
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    comments = instance.comments[:4]
    categories = Category.objects.all()[:10]
    cate_more = Category.objects.all()[11:]
    cate_1 = Category.objects.all()[:5]
    cate_2 = Category.objects.all()[6:]
    locurl = 'http://api.openweathermap.org/data/2.5/weather?q={}&APPID=43e8c934e7122d5b40a25fe6b66c7390'
    city = "lagos"
    r = requests.get(locurl.format(city)).json()
    city_weather = {
        'city': city,
        'temperature': r['main']['temp'],
        'description': r['weather'][0]['description'],
        'icon': r['weather'][0]['icon'],
    }
    context = {
        "article": instance, "comments": comments, "comment_form": comment_form, "obj": obj, "category": category,
        "related_post": related_post, 'categories': categories, "common_tags": common_tags, "cate_1": cate_1,
        "cate_2": cate_2, "city_weather": city_weather, "cate_more": cate_more
    }
    return render(request, 'news-details.html', context)


def article_list(request, cat_name):
    categories = Category.objects.all()[:10]
    category = Article.objects.filter(category_ref__name=cat_name)
    cate = Article.objects.filter(category_ref__name=cat_name)[:1]
    cate_1 = Category.objects.all()[:5]
    cate_more = Category.objects.all()[11:]
    cate_2 = Category.objects.all()[6:]
    query = request.GET.get('q')
    if query:
        category = category.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query) |
            Q(author__last_name__icontains=query)
        ).distinct()
    paginator = Paginator(category, 15) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&APPID=43e8c934e7122d5b40a25fe6b66c7390'
    city = "lagos"
    r = requests.get(url.format(city)).json()
    city_weather = {
        'city': city,
        'temperature': r['main']['temp'],
        'description': r['weather'][0]['description'],
        'icon': r['weather'][0]['icon'],
    }
    context = {
         "categories": categories, "cate": cate, "cate_1": cate_1, "cate_2": cate_2,
         'page_obj': page_obj, "city_weather": city_weather, "cate_more": cate_more
    }
    return render(request, "listing.html", context)


def contact_us(request):
    articles = Article.objects.all().order_by('-created_on')[:5]
    categories = Category.objects.all()[:10]
    cate_more = Category.objects.all()[11:]
    cate_1 = Category.objects.all()[:5]
    cate_2 = Category.objects.all()[6:]
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&APPID=43e8c934e7122d5b40a25fe6b66c7390'
    city = "lagos"
    r = requests.get(url.format(city)).json()
    city_weather = {
        'city': city,
        'temperature': r['main']['temp'],
        'description': r['weather'][0]['description'],

articles/templates/control_newsletter.html
{% extends 'base_sample.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
			<div class="page-breadcrumbs">
				<h1 class="section-title title">Newsletter</h1>
			</div>
    <form method="POST"> {% csrf_token %}
        {{ form| crispy }}
        <button type="submit" name="subscribe" id="subscribe" >Save</button>
    </form>

</div>
{% endblock %}

articles/templates/listing.html
{% extends 'base_sample.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
		<div class="container">

			<div class="page-breadcrumbs">
					 {% for article in cate %}
				<h1 class="section-title">{{ article.category_ref }}</h1>
					{% endfor %}
						<div class="row">
							<div class="col-sm-12">
								<div class="section">
									<div class="row">
                                        {% for article in page_obj %}
										<div class="col-md-6 col-lg-4">
											<div class="post medium-post">
												<div class="entry-header">
													<div class="entry-thumbnail">
														<img class="img-fluid"  style="min-height:200px; max-height:200px; min-width: 100%;" src="{{article.image.url}}" alt="" />
													</div>
												</div>
												<div class="post-content">
													<div class="entry-meta">
														<ul class="list-inline">
															<li class="publish-date"><a href="#"><i class="fa fa-clock-o"></i>{{ article.created_on }}</a></li>
															<li class="views"><a href="#"><i class="fa fa-eye"></i>{{ article.viewcount }}</a></li>
															 <li class="loves"><a onclick="like({{ article.id }})"><i
                                                            class="fa fa-heart-o"></i><span
                                                            id="like_id">{{ article.likecount }}</span></a></li>
														</ul>
													</div>
													<h2 class="entry-title">
														<a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
													</h2>
												</div>
											</div><!--/post-->
										</div>
                                        {% endfor %}
									</div>
								</div><!--/.section -->

								<div class="google-add">
									<div class="add inner-add text-center">
										<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
											<!-- horizontal ads -->
											<ins class="adsbygoogle"
												 style="display:block"
												 data-ad-client="ca-pub-3270488626206393"
												 data-ad-slot="9753307725"
												 data-ad-format="auto"
												 data-full-width-responsive="true"></ins>
											<script>
												 (adsbygoogle = window.adsbygoogle || []).push({});
											</script>
									</div><!--/.section-->
								</div><!--/.google-add-->
							</div>
						</div>
						<div class="pagination-wrapper">
							<ul class="pagination">
							 {% if page_obj.has_previous %}
								<a href="?page=1"></a>
								<li><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous"><span aria-hidden="true"><i class="fa fa-long-arrow-left"></i> Previous Page</span></a></li>
								 {% endif %}

								<li class="active"><a>{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}. </a></li>

							{% if page_obj.has_next %}
								<li><a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Next"><span aria-hidden="true">Next Page <i class="fa fa-long-arrow-right"></i></span></a></li>
								<a href="?page={{ page_obj.paginator.num_pages }}"></a>
							 {% endif %}
							</ul>
						</div>
					</div><!--/.col-sm-9 -->
					</div>
				</div>
			</div><!--/.section-->
		</div><!--/.container-->
	</div><!--/#main-wrapper-->
{% endblock %}
{% block js %}
    <script type="text/javascript">
        function like(article_id) {
            var data = {
                'article': article_id,
                'status': 'article'
            };
            $.get('{% url 'articles:option' 'like' %}', data)
                .done(function (response) {
                    $('#like_id').text(response.like_count)
                })
                .fail(function (error) {

                });
        }
    </script>
{% endblock %}

articles/templates/log_reg_base.html
<!DOCTYPE html>
{% load static %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

    <!--title-->
    <title>The Latest News from Nigeria & Around the World </title>

	<!--CSS-->
   <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/subscribe-better.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link id="preset" rel="stylesheet" type="text/css" href="{% static 'css/presets/preset1.css' %}">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

	<!--Google Fonts-->
	<link href="https://fonts.googleapis.com/css?family=Signika+Negative:400,300,600,700" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
	    <script src="js/html5shiv.js"></script>
	    <script src="js/respond.min.js"></script>
    <![endif]-->
     <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">
</head><!--/head-->

<body>
	<div id="main-wrapper" class="homepage">
		<header id="navigation">
			<div class="navbar navbar-expand-lg" role="banner">
				<div class="container">
					  <a class="secondary-logo" href="{% url 'articles:home' %}">
                         <img class="img-fluid" src="{% static 'images/presets/preset1/logo.png' %}" alt="logo">
                      </a>
				</div>
				<div class="topbar">
					<div class="container">
						<div id="topbar" class="navbar-header">
							  <a class="navbar-brand" href="{% url 'articles:home' %}">
                                     <img class="main-logo img-fluid" src="{% static 'images/presets/preset1/logo.png' %}"
                                                        alt="logo">
                              </a>
							<div id="topbar-right">
								<!--<div class="dropdown language-dropdown">
									<a data-toggle="dropdown" href="#"><span class="change-text">En</span> <i class="fa fa-angle-down"></i></a>
									<ul class="dropdown-menu language-change">
										<li><a href="#">EN</a></li>
										<li><a href="#">FR</a></li>
										<li><a href="#">GR</a></li>
										<li><a href="#">ES</a></li>
									</ul>
								</div>-->
								<div id="date-time"></div>
								<div id="weather">
									<span class="weather-icon">
							      		<img src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Icon" class="img-fluid">
									</span>
							      	<span class="temp">{{ city_weather.city}}</span>
							      	<span class="temp">{{ city_weather.temperature}}°F</span>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div id="menubar" class="container">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"><i class="fa fa-align-justify"></i></span>
					</button>
					<a class="navbar-brand d-lg-none" href="{% url 'articles:home' %}">
                        <img class="main-logo img-fluid" src="{% static 'images/presets/preset1/logo.png' %}" alt="logo">
                    </a>
					<nav id="mainmenu" class="navbar-left collapse navbar-collapse">
						 <ul class="nav navbar-nav">
                                 <li class="home dropdown"><a href="{% url 'articles:home' %}" >Home</a></li>
                                {% if categories %}
                                    {% for cat in categories %}
                                        <li class="lifestyle"> <a href="{% url 'articles:list' cat.name %}">{{ cat.name |capfirst  }}</a></li>
                                {% endfor %}
                                {% endif %}
                                <li class="more dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Pages +</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="{% url 'articles:about' %}">About Us </a></li>
                                        <li><a href="{% url 'articles:terms' %}">Terms of Use </a></li>
                                        <li><a href="{% url 'articles:contact_us' %}">Contact Us </a></li>
                                        <li><a href="{% url 'articles:advert' %}">Advertisement </a></li>
                                    </ul>
                                </li>
                         </ul>
					</nav>
                </div>
			</div>
		</header><!--/#navigation-->
        {% block content %}

        {% endblock %}

	</div><!--/#main-wrapper-->

<footer id="footer">
    <div class="footer-top">
        <div class="container text-center">
            <div class="logo-icon"><img class="img-fluid" src="{% static 'images/presets/preset1/logo-icon.png' %}"
                                        alt=""/></div>
        </div>
    </div>
    <div class="footer-menu">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'articles:home' %}">Home</a></li>
                <li><a href="{% url 'articles:about' %}">About</a></li>
                <!--<li><a href="#">Career</a></li>-->
                <li><a href="{% url 'articles:advert' %}">Advertisement</a></li>
                <li><a href="{% url 'articles:terms' %}">Terms of Use</a></li>
                <li><a href="{% url 'articles:contact_us' %}">Contact Us</a></li>
            </ul>
        </div>
    </div>
    <div class="bottom-widgets">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="widget">
                        <h2>Category</h2>
                        <ul>
                            {% if categories %}
                               {% for cat in cate_1 %}
                            <li><a href="{% url 'articles:list' cat.name %}">{{ cat.name |capfirst  }}</a></li>
                              {% endfor %}
                        {% endif %}
                        </ul>
                        <ul>
                            {% if categories %}
                               {% for cat in cate_2 %}
                            <li><a href="{% url 'articles:list' cat.name %}">{{ cat.name |capfirst  }}</a></li>
                              {% endfor %}
                        {% endif %}
                        </ul>
                    </div>
                </div>

                <div class="col-md-5">
                    <div class="widget">
                        <h2>Tag</h2>
                        <ul>
                            <li><a href="#">Gallery</a></li>
                            <li><a href="#">Sports</a></li>
                            <li><a href="#">Featured</a></li>
                            <li><a href="#">World</a></li>
                            <li><a href="#">Fashion</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Environment</a></li>
                            <li><a href="#">Health</a></li>
                            <li><a href="#">Entertainment</a></li>
                            <li><a href="#">Lifestyle</a></li>
                            <li><a href="#">Business</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Tech</a></li>
                            <li><a href="#">Movie</a></li>
                            <li><a href="#">Music</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="widget">
                        <h2>Featured</h2>
                        <ul>
                            <li><a href="#">UK News</a></li>
                            <li><a href="#">US News</a></li>
                            <li><a href="#">Climate</a></li>
                            <li><a href="#">Offbeat</a></li>
                            <li><a href="#">Health</a></li>
                        </ul>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.container -->
    </div>
    <div class="footer-bottom">
        <div class="container text-center">
            <p><a href="#" style="font-weight:bold;">&copy; Copyright 2017 - {% now "Y" %}</a> | <a href="{% url 'articles:home' %}" style="font-weight:bold;"> Hipsterblog.com.ng</a> | <a href="#" style="font-weight:bold;">All Right Reserved</a> </p>
        </div>
    </div>
</footer>

	<!--/#scripts-->
    <script data-cfasync="false" src="{% static 'cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/moment.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-kit.min.js' %}"></script>
	<script src="{% static 'js/jquery.easy-ticker.min.js' %}"></script>
	<script src="{% static 'js/jquery.subscribe-better.min.js' %}"></script>
	<script src="{% static 'js/theia-sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/switcher.js' %}"></script>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-73239902-1', 'auto');
	  ga('send', 'pageview');
	</script>
</body>
</html>

articles/templates/profile.html
 {% extends 'base_sample.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    {% for obj in user %}
        {{ obj.username }}
    {% endfor %}
 {% endblock %}

articles/templates/signup_newsletter.html
<!doctype html>
<html>
<head>
</head>
<body>
<h2>Welcome to Hipsterblog News Newsletter</h2>
<p>Thank you for joining our newsletter</p>
<p>Visit our website: <a href="https://histerblog.com.ng">Hipsterblog News</a></p>
</body>
</html>